modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "dbmee"
version = "${file.jarVersion}"
displayName = "Don't Break My Ender Eyes"
authors = "3C Team"
description = "Makes thrown Eyes of Ender never break. Configurable shatter chance."
logoFile = "assets/dbmee/icon.png"

[[mixins]]
config = "dbmee.mixins.json"

[[dependencies.dbmee]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dbmee]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"
